import React,{useEffect,useRef,useState,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {AbsoluteFill,Img,interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
import {Player} from '@remotion/player';
export const TOTAL=600;
export const acts=[['The idea','One product. More ways to tell its story.','At 2xROAS, Inc., we built PumpAds to turn a product brief into creator-style video ads.'],['The creative','Find the hook. Give it a voice.','LLM scripts, voice generation, and image and video models came together in one creative workflow.'],['The production','Make the moving parts work together.','Lip sync, revoicing, and FFmpeg assembly turned separate generations into finished ads.'],['The business','Build something people will pay for.','Together, we reached 1,000+ paying customers and $15K in monthly revenue within two months of launch.']];
const creators=[{src:'/assets/pumpads-skincare.png',label:'01 / skincare',line:'A little moment for yourself.',alt:'Fictional adult creator presenting a skincare bottle'},{src:'/assets/pumpads-tumbler.png',label:'02 / everyday essentials',line:'Meet your new morning companion.',alt:'Fictional adult creator holding a travel tumbler'},{src:'/assets/pumpads-headphones.png',label:'03 / audio',line:'Make room for your favorite sound.',alt:'Fictional adult creator presenting headphones'}];
const clamp=x=>Math.max(0,Math.min(1,x));
export function PumpFilm({compact=false}){
 const f=useCurrentFrame(),{width:w}=useVideoConfig(),act=Math.min(3,Math.floor(f/150)),t=f%150;
 const fan=1-clamp(f/130),focus=interpolate(f,[0,170,230,370,430,599],[0,0,1,1,2,2],{extrapolateRight:'clamp'});
 return <AbsoluteFill style={{background:'#eeedeb',color:'#3c3c3c',fontFamily:"'Caveat',cursive",lineHeight:1.2,overflow:'hidden'}}>
  <div style={{position:'absolute',left:30,right:30,top:22,display:'flex',justifyContent:'space-between',fontSize:compact?25:22,borderBottom:'1px solid #bcbcb7',paddingBottom:15}}><span>PumpAds / creative studio</span><span>0{act+1} / 04</span></div>
  {creators.map((c,i)=>{
   const cw=compact?390:280,ch=compact?585:420;
   const center=compact?w/2+(i-focus)*310:225+i*375;
   const y=compact?135:95+(i===1?0:fan*15);
   const lift=Math.sin((f+i*40)/65)*(compact?3:6);
   const arrival=clamp((f-i*10+35)/70);
   return <div key={c.src} style={{position:'absolute',width:cw,height:ch,left:center-cw/2,top:y+lift+(1-arrival)*20,opacity:compact?(1-Math.min(1,Math.abs(i-focus))*.57):arrival,transform:`rotate(${compact?(i-focus)*5:(i-1)*fan*8}deg) scale(${compact?1-Math.min(1,Math.abs(i-focus))*.12:1})`,zIndex:compact?(i===Math.round(focus)?3:1):(i===1?3:2),border:'6px solid #faf9f6',borderRadius:12,boxShadow:'0 16px 36px #00000020',overflow:'hidden'}}>
    <Img src={c.src} alt={c.alt} style={{width:'100%',height:'100%',objectFit:'cover',filter:'grayscale(1)',transform:`scale(${1.02+clamp(f/TOTAL)*.075}) translateY(${-Math.sin(f/160+i)*3}px)`}}/>
    <div style={{position:'absolute',inset:0,background:'linear-gradient(transparent 44%, #000000bb 100%)'}}/>
    <span style={{position:'absolute',top:15,left:15,right:15,fontSize:compact?23:19,color:'#fff',textShadow:'0 1px 6px #000'}}>{c.label}</span>
    <div style={{position:'absolute',bottom:25,left:19,right:19,color:'#fff'}}><span style={{fontSize:compact?20:17,opacity:.85}}>{act===0?'a product to talk about':act===1?'the opening hook':act===2?'assembling the story':'a creative ready to share'}</span><div style={{fontSize:compact?39:32,marginTop:8,minHeight:compact?96:77}}>{act===0?['A daily ritual.','Out the door.','Into your world.'][i]:act===1?c.line.slice(0,Math.floor(clamp((t-i*8)/80)*c.line.length)):c.line}</div><div style={{height:3,background:'#ffffff44',marginTop:15}}><div style={{height:'100%',width:`${clamp((f+40-i*15)/TOTAL)*100}%`,background:'#fff'}}/></div></div>
   </div>;
  })}
  <div style={{position:'absolute',left:30,right:30,bottom:compact?78:85,textAlign:'center',fontSize:compact?31:29}}>{act===0?'product brief → creative directions':act===1?'script → voice → visual':act===2?'lip sync → assembly → final ad':'from 10 minutes to 2 minutes per generation'}</div>
  <div style={{position:'absolute',left:30,right:30,bottom:25,fontSize:compact?23:19,textAlign:'center',color:'#747474'}}>Illustrative AI creator concepts · not customer campaigns</div>
 </AbsoluteFill>;
}
function PumpStory(){
 const player=useRef(null),track=useRef(null),raf=useRef(0),visible=useRef(false),running=useRef(false),position=useRef(0);
 const [frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[compact,setCompact]=useState(()=>matchMedia('(max-width:650px)').matches),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion:reduce)').matches),[reading,setReading]=useState(false);
 const still=reduced||reading,act=Math.min(3,Math.floor(frame/150)),props=useMemo(()=>({compact}),[compact]);
 const pause=()=>{player.current?.pause();running.current=false;setPlaying(false);};
 const seek=n=>{n=Math.max(0,Math.min(TOTAL-1,Math.round(n)));position.current=n;setFrame(n);player.current?.seekTo(n);};
 useEffect(()=>{const a=matchMedia('(max-width:650px)'),b=matchMedia('(prefers-reduced-motion:reduce)');const change=()=>{setCompact(a.matches);setReduced(b.matches);};a.addEventListener('change',change);b.addEventListener('change',change);return()=>{a.removeEventListener('change',change);b.removeEventListener('change',change);};},[]);
 useEffect(()=>{if(still)return;const p=player.current;const update=e=>{position.current=e.detail.frame;setFrame(e.detail.frame);},end=()=>{running.current=false;setPlaying(false);};p.addEventListener('frameupdate',update);p.addEventListener('ended',end);return()=>{p.removeEventListener('frameupdate',update);p.removeEventListener('ended',end);};},[still,compact]);
 useEffect(()=>{if(still)return;const scroll=()=>{if(raf.current)return;raf.current=requestAnimationFrame(()=>{raf.current=0;if(!visible.current||running.current||matchMedia('(max-height:620px) and (min-width:651px)').matches)return;const rect=track.current.getBoundingClientRect();seek(clamp(-rect.top/Math.max(1,track.current.offsetHeight-innerHeight))*(TOTAL-1));});};const observer=new IntersectionObserver(([e])=>{visible.current=e.isIntersecting;if(e.isIntersecting)scroll();else pause();});observer.observe(track.current);const hide=()=>{if(document.hidden)pause();};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);document.addEventListener('visibilitychange',hide);return()=>{observer.disconnect();removeEventListener('scroll',scroll);removeEventListener('resize',scroll);document.removeEventListener('visibilitychange',hide);cancelAnimationFrame(raf.current);raf.current=0;};},[still]);
 return <><div ref={track} className={`pump-track ${still?'pump-still':''}`}><div className="pump-sticky">{still?<><div className="pump-gallery">{creators.map(c=><figure key={c.src}><img src={c.src} alt={c.alt}/><figcaption>{c.label}</figcaption></figure>)}</div><p className="pump-example-note">Illustrative AI creator concepts · not customer campaigns</p><ol className="pump-readable">{acts.map(a=><li key={a[0]}><h3>{a[1]}</h3><p>{a[2]}</p></li>)}</ol></>:<><div className="pump-caption"><span>0{act+1} / {acts[act][0]}</span><h3>{acts[act][1]}</h3><p>{acts[act][2]}</p></div><div className="pump-cinema"><Player ref={player} component={PumpFilm} inputProps={props} durationInFrames={TOTAL} fps={30} compositionWidth={compact?760:1200} compositionHeight={compact?850:650} style={{width:'100%'}} controls={false} autoPlay={false} clickToPlay={false} doubleClickToFullscreen={false} spaceKeyToPlayOrPause={false} acknowledgeRemotionLicense/></div><div className="pump-controls"><button type="button" onClick={()=>{if(running.current){pause();return;}if(position.current>=TOTAL-2)seek(0);running.current=true;setPlaying(true);player.current?.play();}}>{playing?'Ⅱ Pause story':'▷ Play story'}</button><label><span className="sr-only">PumpAds animation position</span><input type="range" min="0" max={TOTAL-1} value={frame} aria-valuetext={acts[act][0]} onChange={e=>{pause();seek(+e.target.value);}}/></label><span>{Math.floor(frame/30)} / 20s</span></div><nav className="pump-chapters" aria-label="PumpAds story chapters">{acts.map((a,i)=><button key={a[0]} aria-current={act===i?'step':undefined} onClick={()=>{pause();seek(i*150+65);}}>{a[0]}</button>)}</nav><p className="pump-hint">Scroll to create the next frame.</p></>}</div></div><button className="pump-read-toggle" type="button" disabled={reduced} onClick={()=>{pause();setReading(!reading);}}>{reduced?'Motion reduced to match your device':reading?'Show the animated cards':'Read without animation'}</button></>;
}
const mount=typeof document==='undefined'?null:document.getElementById('pumpads-story');if(mount)createRoot(mount).render(<PumpStory/>);
